### ISSUE TITLE
JFRD - jlink support

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-jfr-core#111]
jlink is a tool that generates a custom Java runtime image that contains only the platform modules that are required for a given application. With jlink support, we can ship a bundled JRE with the JFR-daemon and thus simplify deployment of the RTP solution.

A [<ins>PR</ins>](https://github.com/newrelic/newrelic-jfr-core/pull/78) is ready that contains the bulk of this work. It was not ready until just before the RTP launch, and so we decided not to include it at that time, with the intention of releasing it soon thereafter.

As part of this work which will require a release of the JFR-daemon, we intend to also beta support for data gathering - 1 extra event type, as well as locks + JDK errors events

See this [doc](https://docs.google.com/document/d/1K9QqT-G7nQQJImlknhkotf9QhbTVFI0NagXT3xris-o/edit?usp=sharing)

Aha! Link: https://newrelic.aha.io/features/JAVA-202

**Comment by kford-newrelic** [comment]
Agreement in the PM planning session is to take this as far as possible during the current week but to pause wherever we are by 12/18. If not complete at that point, may possibly be carried over as Feb commit.
