### ISSUE TITLE
Add notice of currently known issue: Flamegraphs don't work with JFRD-only deployments

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-jfr-core#113]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

Flamegraphs do not appear for deployments where the jfr daemon is installed without the Java agent.

## Expected Behaviour

At a minimum, need to provide guidance to users that this is a known issue until it is fixed.

**Comment by XiXiaPdx** [comment]
docs updated
