### ISSUE TITLE
read_multiple_real_events fails with java 14

### ISSUE THREAD

**Issue by gfuller1** [newrelic/newrelic-jfr-core#121]
When running `./gradlew build`, `read_multiple_real_events` fails with the message `org.opentest4j.AssertionFailedError: expected: <105.0> but was: <111.0>`. If java 14 doesn't work with this daemon we should either document it or fix it.

To repro just use java 14 and run `./gadlew build`.

**Comment by jack-berg** [comment]
I dug into this a bit and it appears that the way that JFR interprets `.jfr` file data changes in some way from Java 11 -> 14. In the case of this test, the file being processed is `/jfr-mappers/src/test/resources/startup3.jfr`. Garbage collection data is being read and summarized from this file. The `RecordedEvent#getStartTime().toEpochMilli()` accessor returns slightly different values in different java versions. 

Maybe we could fix this by asserting that the value is within a range? Or maybe we could have the assertion change based on whether java 11 or 14 is running?

**Comment by kford-newrelic** [comment]
Not selected for the agent roadmap.
