### ISSUE TITLE
Publish jlink jfr daemon packages

### ISSUE THREAD

**Issue by jack-berg** [newrelic/newrelic-jfr-core#132]
Work has been done to be able to build a executable binary for the jfr-daemon via jlink. See `./gradlew jlink`. 

A strategy around packaging and publication still must be worked out and executed. Originally, work was done to be able to produce `.rpm` and `.deb` within this project using a custom gradle plugin. However, that has been rolled back because gradle may not be the best place to handle building native binaries for various platforms and various package managers.

**Comment by jack-berg** [comment]
This issue is currently `waiting`. We're waiting on New Relic to develop a strategy around packaging and publishing native binaries that we can leverage.

**Comment by kford-newrelic** [comment]
Not chosen for the go-forward agent roadmap.
