### ISSUE TITLE
Enable jfr as a javaagent

### ISSUE THREAD

**Issue by jack-berg** [newrelic/newrelic-jfr-core#134]
Currently jfr can be run as a daemon process or as an agent extension. This task is to package it so that it can be run as standalone java agent via `java -jar -javaagent:/newrelic-jfr-agent.jar app.jar`. 

@kittylyst previously had a PR that demonstrated this: https://github.com/newrelic/newrelic-jfr-core/pull/116

After the [java 8 backport](https://github.com/newrelic/newrelic-jfr-core/issues/133) is completed, the branch should be rebased and completed.

**Comment by kford-newrelic** [comment]
Delivered in agent version 7.0.0
