### ISSUE TITLE
Enable support of HTTPS proxy

### ISSUE THREAD

**Issue by alx13** [newrelic/newrelic-jfr-core#147]
## Is your feature request related to a problem? Please describe.
NewRelic agent is able to use HTTP/S proxy to send data to NewRelic endpoints, but jfr-daemon is not.

## Feature Description
Add environment variables `NEW_RELIC_PROXY_HOST` and `NEW_RELIC_PROXY_PORT` to configure usage of HTTP proxy

## Describe Alternatives
We can use `-Dhttps.proxyHost` and `-Dhttps.proxyPort` java args.

## Priority
Nice to have

**Comment by XiXiaPdx** [comment]
@alx13  This request is being tracked in #167 now. Thanks for suggesting it!
