### ISSUE TITLE
JFRD - support for Java 8

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-jfr-core#148]
We want to make it very easy for our existing customers using the Java agent to turn on Real Time Profiling (RTP), provide more options to deploy in container environments, reduce pre-reqs (& align to majority of our customers’ environments) ….

There is a progression of work that will first simplify deployment of RTP for NR Java agent customers and then for customers that opt not to use the Java agent due to performance reasons but want to get the low-overhead insights available from RTP. Each step provides incremental value, and we can opt to stop at any point:

1. JFRD to be compatible with Java 8
2. JFR as an extension to the agent - single process, streamline configuration
3. JFR to be used as a standalone without a separate process

**Acceptance Criteria**

- JFRD will run in Java 8 environment
- Update docs with support for proxies
- Add metrics: new JFR event types
  - new GC metrics -
    - GC Major Collection Count
    - GC Minor Collection Count
    - GC Major Collection Time
    - GC Minor Collection Time
    - GC ParNew Time
  - Others TBD
- new release of JFRD

Aha! Link: https://newrelic.aha.io/features/JAVA-233

**Comment by jasonjkeller** [comment]
https://github.com/newrelic/newrelic-jfr-core/pull/143
