### ISSUE TITLE
Add BasicGarbageCollectionSummarizer to JFRD 

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-jfr-core#150]
## Is your feature request related to a problem? Please describe.
Want access to detailed GC metrics for resource utilization analysis.

## Feature Description
Want access to these metrics:
- GC Major Collection Count
- GC Minor Collection Count
- GC Major Collection Time
- GC Minor Collection Time
- ~~GC ParNew Time~~.  Minor Collection Time is the same as ParNew. 

A lot of these details came out of [this slack conversation](https://newrelic.slack.com/archives/CV2EXQQA2/p1614867279019000) with Ben 

JFR produces the `jdk.GarbageCollection` GC event 

```
jdk.GarbageCollection {
  startTime = 11:52:18.076
  duration = 0.502 ms
  gcId = 859
  name = "G1New"
  cause = "G1 Evacuation Pause"
  sumOfPauses = 0.502 ms
  longestPause = 0.502 ms
}
```

To capture these vents, create a new `BasicGarbageCollectionSummarizer` in JFRD to accept these events and summarize into Summary metrics.    The `EVENT_NAME` of the summarizer will be `jdk.GarbageCollection`

There will be 4 new metrics created from this summarizer. 

`jfr.GarbageCollection.minorCount`
`jfr.GarbageCollection.minorDuration`
`jfr.GarbageCollection.majorCount`
`jfr.GarbageCollection.majorDuration`

The `name` field of the event specifies which Garbage Collector this data is for (i.e. G1, CMS, Parallel) and if it is Major (old) or Minor(young) event.    "G1New" here means a young event. When multiple garbage collectors are in use, for example when Parallel (`name` = ParNew) and G1 (`name` = G1New), both events will feed into one metric - `jfr.GarbageCollection.minorCount`

 The `name` field is important as it will determine if JFRD supports including the event in the summary metric. 

First

 Test JFR with all 3 mainstream collectors  - Parallel, CMS, G1 - to generate and examine the raw JFR events. Need to see the structure of the data, especially the `name` value.  Verify the name for Old and Young events for all three collectors. 

Second 

Add the new summarizer to JFRD and manually test for all three different collector scenarios. 

## Priority
Must Have

**Comment by XiXiaPdx** [comment]
JFR produces the `jdk.GarbageCollection` GC event 

The `name` field specifies which Garbage Collector this data is for (i.e. G1, CMS, Parallel) and if it is Major (old) or Minor(young) event.    "New" here means a young event. 

The `name` field is important as it will be how JFRD decides if a summarizer should accept it. 

```
jdk.GarbageCollection {
  startTime = 11:52:18.076
  duration = 0.502 ms
  gcId = 859
  name = "G1New"
  cause = "G1 Evacuation Pause"
  sumOfPauses = 0.502 ms
  longestPause = 0.502 ms
}
```

To capture these vents, create a new `BasicGarbageCollectionSummarizer` in JFRD to accept these events and summarize into Summary metrics.   

The `EVENT_NAME` of the summarizer will be `jdk.GarbageCollection`

There will be 4 new metrics created from this summarizer. 

`jfr.GarbageCollection.minorCount`
`jfr.GarbageCollection.minorDuration`
`jfr.GarbageCollection.majorCount`
`jfr.GarbageCollection.majorDuration`

When multiple garbage collectors are in use, for example when Parallel (`name` = ParNew) and G1 (`name` = G1New), both events will feed into one metric - `jfr.GarbageCollection.minorCount`

First

 Test JFR with all 3 mainstream collectors  - Parallel, CMS, G1 - to generate and examine the raw JFR events. Need to see the structure of the data, especially the `name` value.  Verify the name for Old and Young events for all three collectors. 

Second 

Add the new summarizer to JFRD and manually test for all three different collector scenarios.

**Comment by jasonjkeller** [comment]
GC implementations:
- Serial Garbage Collector: `-XX:+UseSerialGC`
- Parallel Garbage Collector: `-XX:+UseParallelGC`
- CMS Garbage Collector: `-XX:+UseParNewGC` / `-XX:+UseConcMarkSweepGC`
- G1 Garbage Collector: `-XX:+UseG1GC`

https://www.baeldung.com/jvm-garbage-collectors

**Comment by jasonjkeller** [comment]
Here's a list of all of the GC Names and which major version of Java they were added in.

[JDK 12](https://github.com/openjdk/jdk/blob/jdk-12+33/src/hotspot/share/gc/shared/gcName.hpp)

```
Shenandoah
```

[JDK 11](https://github.com/openjdk/jdk/blob/jdk-11+28/src/hotspot/share/gc/shared/gcName.hpp)

```
Z
N/A
```

[JDK 10](https://github.com/openjdk/jdk/blob/jdk-10%2B46/src/hotspot/share/gc/shared/gcName.hpp)

```
G1Full
```

[JDK 8](https://github.com/openjdk/jdk/blob/jdk8-b120/hotspot/src/share/vm/gc_interface/gcName.hpp)

```
ParallelOld
SerialOld
PSMarkSweep
ParallelScavenge
DefNew
ParNew
G1New
ConcurrentMarkSweep
G1Old
GCNameEndSentinel
```

**Comment by XiXiaPdx** [comment]
Nice find!

**Comment by jasonjkeller** [comment]
We'll proceed with the following breakdown and log on ignored.

`jfr.GarbageCollection.minorDuration`

```
DefNew
ParNew
G1New
PSMarkSweep
ParallelScavenge
```

`jfr.GarbageCollection.majorDuration`

```
ParallelOld
SerialOld
G1Old
ConcurrentMarkSweep
G1Full
```

Ignored

```
N/A
GCNameEndSentinel
Shenandoah
Z 
```
