### ISSUE TITLE
Coexist with explicitly started JFR recording

### ISSUE THREAD

**Issue by kittylyst** [newrelic/newrelic-jfr-core#153]
Some customers want to run JFR recordings alongside the daemon or agent. Our code should be able to happily coexist with other JFR recordings running simultaneously. 

## Priority

Really Want

**Comment by Stephan202** [comment]
Hi @kittylyst. Does this issue mean that explicitly started recordings currently don't work if the New Relic JFR integration is active, or that such explicitly started recordings negatively affect the data submitted to New Relic?

**Comment by kittylyst** [comment]
Hi @Stephan202 this issue was really just an aide-memoire to remember to check the behaviour of the agent when used in conjunction with an explicit recording flag. It *should* work, but I don't think that anyone checked in detail yet.

I should also say that I've moved on from New Relic now, so the team will need to pick this one up.

**Comment by kford-newrelic** [comment]
Tested by the team - the agent JFR feature works fine with any other JFR recordings that are being done simultaneously.
