### ISSUE TITLE
Update Smoke Test testcontainers to run with Java 8

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#157]
The image for the testcontainers in the smoke tests are built with Java 11. 

https://github.com/newrelic/newrelic-jfr-core/blob/7f6c163953cf6aae6336297827efe717ec82f2b3/smoke-tests/src/test/java/com/newrelic/smoke/SmokeTestBase.java#L28

Update to Java 8 and confirm tests pass.

**Comment by jasonjkeller** [comment]
This is done
