### ISSUE TITLE
Add docs for running a proxy when using JFRD as daemon

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#158]
We should document for customers on how to configure JFRD as a daemon to work with their proxy. 

This will involve setting up a proxy, testing, and documenting.   

For this issue - #147

**Comment by jasonjkeller** [comment]
See: https://github.com/newrelic/newrelic-jfr-core/issues/147

**Comment by XiXiaPdx** [comment]
The current docs point out the generic way to set proxy configurations that affect all connections on a JVM.  This issue is for setting up a proxy config specific to the jfr-daemon and the underlying Telemetry SDK #167
