### ISSUE TITLE
Add doc for consuming Jlink binary of JFRD with a package manager

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#159]
This is dependent on @kittylyst and friends figuring out publishing the JFRD JLink binary.  My understanding is the goal is to publish the binary to downloads.newrelic.com so that customers can use their respective package managers to consume the binary. 

I'm not familiar with this process so apologies for any confusing or incorrect terminology! Feedback welcome to clarify and improve this issue. 

Once JLink binary is published, test the process as a customer to consume the binary and document.

**Comment by jasonjkeller** [comment]
@XiXiaPdx This story isn't a blocker for the current milestone is it? Should it be removed from "JFRd support for Java 8"?

**Comment by XiXiaPdx** [comment]
> @XiXiaPdx This story isn't a blocker for the current milestone is it? Should it be removed from "JFRd support for Java 8"?


good call, removed!

**Comment by jasonjkeller** [comment]
Closing for now. We'll revisit when the jlink work is done.
