### ISSUE TITLE
Review docs and improve clarity on where in NR JFRD daemon data will report to

### ISSUE THREAD

**Issue by XiXiaPdx** [newrelic/newrelic-jfr-core#160]
The current docs for JFRD as daemon calls out where data will be reported if the Java Agent is present or not. Maybe this can be improved? Less words, a graphic table? 

https://docs.newrelic.com/docs/agents/java-agent/features/real-time-profiling-java-using-jfr-metrics#about

Understand what are current misunderstandings and improve docs to clarify, if possible.

**Comment by jasonjkeller** [comment]
I've got two documentation PRs ready to go once we get the 1.1.0 release out:
* Readme: https://github.com/newrelic/newrelic-jfr-core/pull/170
* Public doc: https://github.com/newrelic/docs-website/pull/1325
