### ISSUE TITLE
JFR Optimization

### ISSUE THREAD

**Issue by jodeev** [newrelic/newrelic-jfr-core#181]
See [doc](https://docs.google.com/document/d/1WYsZawlTDSYmyOHCg_TssrHQWlEed42859aDa0pb7eI/edit#). This includes links to sample data.

We need to optimize the amount of data sent for flamegraphs.

This is a pre-req for 'switching on JFR by default'

Aha! Link: https://newrelic.aha.io/features/JAVA-273

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6968865361031570372)

Engineering work completed; documentation updates in progress.

**Comment by kford-newrelic** [comment]
Comment added by Kevyn Ford in Aha! - [View](https://newrelic.aha.io/comments/6969715867156544949)

JFR optimization development complete
