### ISSUE TITLE
Build failure on windows

### ISSUE THREAD

**Issue by knocksto** [newrelic/newrelic-jfr-core#184]
## Description
building the newrelic-jfr-core with java version 15 produces the error below;
error: package jdk.jfr.consumer does not exist
import jdk.jfr.consumer.RecordedFrame;

## Steps to Reproduce
clone the newrelic-jfr-core repository from github onto your windows machine
open the project in intellij idea
open the terminal within intellij
run "gradle wrapper" to install the gradlew.bat
run "./gradlew.bat build

Note: Ensure you have gradle installed on the windows  machine

## Expected Behaviour
Build successful

## Relevant Logs / Console output
newrelic-jfr-core\jfr-mappers\src\main\java\com\newrelic\jfr\MethodSupport.java:14: error: package jdk.jfr.consumer does not exist
import jdk.jfr.consumer.RecordedFrame;

newrelic-jfr-core\jfr-mappers\src\main\java\com\newrelic\jfr\MethodSupport.java:15: error: package jdk.jfr.consumer does not exist
import jdk.jfr.consumer.RecordedMethod;
.
.
.
NB: there were many errors of such nature.

## Your Environment
64 bits Windows Operating System version 10 Pro
Intellij Idea Ultimate 2019.3.5
gradle version 6.8.3
java version 15.0.2

![image](https://user-images.githubusercontent.com/78961388/114726739-2bde2500-9d2d-11eb-879d-fe6ff05cd5a1.png)

**Comment by kford-newrelic** [comment]
We build on Linux hosts. While building under Windows may work, we don’t directly support Windows as a build platform. Closing issue with no further action.

**Comment by jasonjkeller** [comment]
Make sure that the `bytecode target version` of your java compiler is set correctly in Intellij and that under `Build, Execution, Deployment > Build Tools > Gradle` you have it set to build and run using gradle instead of intellij.
