### ISSUE TITLE
Measure the difference in the amount of data being ingested for JfrMethodSample events vs. FlameLevel events

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-jfr-core#193]
We should have a rough idea of how much the data ingestion has been decreased by the aggregated FlameLevel events versus the JfrMethodSample events.

Simple queries such as the following should hopefully provide a rough estimate.

```
FROM JfrMethodSample SELECT bytecountestimate() WHERE entity.guid = 'xyz123' SINCE 1 day ago RAW
```

```
FROM FlameLevel SELECT bytecountestimate() WHERE entity.guid = 'xyz123' SINCE 1 day ago RAW
```

**Comment by XiXiaPdx** [comment]
Here are some results on test data

https://docs.google.com/document/d/1oELGnEMfSbxKFzAjD8li0U2n7-4KL670223OyVSbz2A/edit#heading=h.pkao7dwxd3g
