### ISSUE TITLE
Release a new version of JFR core and deploy the updated FlameGraph service

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-jfr-core#194]
We will need to release a new version of JFR core with the optimization work and pull it into the Java agent before the 7.0.0 release. We will also need to deploy the latest version of the Flamegraph service supporting these changes.

**Comment by XiXiaPdx** [comment]
Jfr Core 1.3.0 has been released - https://search.maven.org/search?q=newrelic%20jfr
