### ISSUE TITLE
"field does not exist" errors from com.newrelic.jfr.RecordedObjectValidators with jfr-daemon 1.20 and Java agent 7.0.0

### ISSUE THREAD

**Issue by tmancill** [newrelic/newrelic-jfr-core#200]
[NOTE]: # ( ^^ Provide a general summary of the issue in the title above. ^^ )

## Description

My [dropwizard (v2.0.21)](https://github.com/dropwizard/dropwizard/releases/tag/v2.0.21) application is auto-instrumented with the New Relic Java Agent 7.0.0 and is using jfr-daemon 1.2.0.  The following lines appear periodically ion STDERR after startup - for example:

```
[JfrController] ERROR com.newrelic.jfr.RecordedObjectValidators - Field 'succeeded' does not exist on RecordedObject in 'Workarounds'
[JfrController] INFO com.newrelic.jfr.daemon.EventConverter - This conversion had 53 events
[JfrController] INFO com.newrelic.jfr.daemon.JFRUploader - Sending metric batch of size 212
[JfrController] INFO com.newrelic.jfr.daemon.JFRUploader - Sending events batch of size 563
[JfrController] INFO com.newrelic.jfr.daemon.EventConverter - This conversion had 50 events
[JfrController] INFO com.newrelic.jfr.daemon.JFRUploader - Sending metric batch of size 172
[JfrController] INFO com.newrelic.jfr.daemon.JFRUploader - Sending events batch of size 550
[JfrController] ERROR com.newrelic.jfr.RecordedObjectValidators - Field 'when' does not exist on RecordedObject in 'GCHeapSummaryMapper'
[JfrController] ERROR com.newrelic.jfr.RecordedObjectValidators - Field 'when' does not exist on RecordedObject in 'GCHeapSummaryMapper'
...
```

## Steps to Reproduce

1.  Start application and jfr-daemon and observe output.

## Expected Behavior

Errors for unknown fields are not logged.

## Your Environment

* Ubuntu 20.04 LTS
* AdoptOpenJDK 11.0.11
* jfr-daemon 1.2.0
* New Relic Java agent 7.0.0
* Dropwizard 2.0.21

**Comment by meiao** [comment]
Hi @tmancill,
with the Java agent 7.0.0 you no longer need to run a separate jfr-daemon.
The agent now has all the functionality of the jfr-daemon, you just need to enable it.
Check https://github.com/newrelic/newrelic-jfr-core#new-relic-java-agent-jfr-service on how to configure it.

This probably will not fix the error logs, but at least they will be in the `newrelic_agent.log`.

We will investigate why those messages are showing up.

**Comment by tmancill** [comment]
Hi @meiao Thank you for the response.  I have redeployed using the agent, confirmed that I am seeing JFR data flowing, and reviewed the logs and don't see any of those errors.  Therefore, I believe this is already fixed.  Thanks!
