### ISSUE TITLE
Wrong title for card in UI

### ISSUE THREAD

**Issue by meiao** [newrelic/newrelic-jfr-core#216]
## Description

In the Realtime Profiling page in NR1, there is a card with the title: "Large Object Allocation (outside TLAB) per Class".
The title in this card should read "Large Object Allocation (outside TLAB) per Thread".

**Comment by kford-newrelic** [comment]
Following up with UI teams...

**Comment by kford-newrelic** [comment]
Handed off to the Foundations team. Will be resolved as a part of Jira issue https://issues.newrelic.com/browse/NR-26715
