### ISSUE TITLE
The confusion of JFR core daemon implementation

### ISSUE THREAD

**Issue by ToKrystal133** [newrelic/newrelic-jfr-core#217]
Env: jdk11
Hello! I was confusing after I saw the JFR core daemon implementation.It dump the JFR info periodicity and then read events from file.It use the lastEventTime to prevent event lost, it also like streaming to process the events.But I think the event time is not always orderly,because it product at the thread side’s threadlocal buffer and then transfer to the global buffer.It is orderly at each thread self.So at the JFR core daemon side,if thread A product data to file A with time A,then thread B product data to file B with time B, but time B is before than time A, at this time,the events which product by thread B will be ignore.It is a problem?Because I saw the dump file occur the lastEvent’s time is before than middle event’s time.

**Comment by ToKrystal133** [comment]
> 



> @ToKrystal133 thanks for letting us know about this code concern. Just confirming : have you actually run into the issue you described?

Not yet~ I think if the problem exists,it is probabilistic and lost event uncontrollable.

**Comment by kford-newrelic** [comment]
@ToKrystal133 Thanks again for letting us know about this concern. Unfortunately, we don't have the engineering bandwidth available to pursue this. Not added to the product roadmap.
