### ISSUE TITLE
Daemon should support JMX authentication

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-jfr-core#42]
## Summary

Currently, the daemon is not capable of authenticating with the application JMX process.  For security purposes, some users will want JMX to require authentication.  In this mode, the daemon will need to be able to authenticate.

## Desired Behavior

Daemon has the ability to authenticate JMX to the running target application.  Users who do not want or need this extra level of authentication can disable it, and the daemon should support this as well.

## Possible Solution

Some consideration will have to be given on how authentication secrets are handled by the daemon.  Are environment variables good enough here?

## Additional context

Securing the JMX port with authentication will be very important to some customers.

**Comment by jodeev** [comment]
This issue has come up in a couple of customer conversations.

**Comment by kraig-schroth-jamf** [comment]
I too would love to be able to leverage this -- today I'm writing a file to the os with the password stored in it, so being able to define a path/to/txtfile would be useful as well

**Comment by kford-newrelic** [comment]
@kraig-schroth-jamf thank you for the feedback - unfortunately, we will not be able to devote engineering time to this enhancement. Not selected for the agent roadmap.
