### ISSUE TITLE
Should the JFR daemon survive the application restarting?

### ISSUE THREAD

**Issue by breedx-nr** [newrelic/newrelic-jfr-core#61]
Not sure if this is a desired use case.  It currently does not survive a restart of the remote application.  Curious what @abhihub and @kittylyst think.

**Comment by abhihub** [comment]
Reasons to keep:
Doesnt have to be downloaded on every restart. 

Ques:
Is the Daemon being used for multiple JVMs/Applications on the same machine?

Reasons to remove:
Daemon may not be needed post restart. Could use restart as a reason to auto update the daemon to newer version.

**Comment by breedx-nr** [comment]
@abhihub I am confused by this assessment.  
* The daemon is not downloaded on every restart.  It is downloaded once, and then started each time the app is started.
* One daemon per JVM is currently the intended usage.  If we want to explore changes to that, let's do that in a separate issue and not complicate this issue.
* The daemon is what sends data, so it is needed after restart if you want to keep sending data.

All I was asking was whether or not the daemon should stick around and continuously try and reconnect to the target jvm, versus going away itself.

**Comment by aprilla** [comment]
@abhihub what's the use case for leaving the daemon running while the app is down? We need to know if this is required for GA as well.

**Comment by breedx-nr** [comment]
Discussed today and came to an agreement that we can go ahead and shut down the daemon when the app goes away.

**Comment by XiXiaPdx** [comment]
> Discussed today and came to an agreement that we can go ahead and shut down the daemon when the app goes away.

True. Witness

**Comment by breedx-nr** [comment]
It's not pretty, but I did confirm that when the target app is exited, the JFR Daemon will crash and exit.  If folks think that this is too clumsy or should be more graceful, we should open a ticket at that time.

Closing for now.
