### ISSUE TITLE
NrIntegrationErrors being caused by JfrJVMInformation being "rejected because attribute value exceeded maximum length"

### ISSUE THREAD

**Issue by jasonjkeller** [newrelic/newrelic-jfr-core#92]
Looks like we’re getting a bunch of `NrIntegrationError`s being caused by `JfrJVMInformation` events being "rejected because attribute value exceeded maximum length"

Saw these when querying for `NrIntegrationError`s on a service being monitored by version `0.5.0` of the JFR daemon:

```
        {
          "apiKeyPrefix": "NRII-AdfTkg1",
          "category": "EventApiException",
          "eventTypeSample": "JfrJVMInformation",
          "message": "1 event(s) rejected because attribute value exceeded maximum length",
          "name": "EventValidationException",
          "newRelicFeature": "Event API",
          "requestId": "9fdd62fc-0034-b000-0000-01756ba0b06e",
          "timestamp": 1603828494446
        }
```

Looks like we'll need to do some additional validation around attribute size.

**Comment by jasonjkeller** [comment]
It's likely the `jvmArguments` attribute that is the issue here, though `javaArguments` could potentially be problematic as well (though I don't think it is currently included in the [events that we create](https://github.com/newrelic/newrelic-jfr-core/blob/main/jfr-mappers/src/main/java/com/newrelic/jfr/toevent/JVMInformationMapper.java#L42-L44)). Here is an event from JFR:

```
jdk.JVMInformation {
  startTime = 12:15:43.752

  jvmName = "OpenJDK 64-Bit Server VM"

  jvmVersion = "OpenJDK 64-Bit Server VM (11.0.8+10) for bsd-amd64 JRE (11.0.8+10), built on Jul 15 2020 09:55:29 by "jenkins" with gcc 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.46.4)"

  jvmArguments = "-javaagent:/Users/jkeller/agents/newrelic_snapshot_build/newrelic.jar -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1099 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -XX:TieredStopAtLevel=1 -Xverify:none -Dspring.output.ansi.enabled=always -Dcom.sun.management.jmxremote -Dspring.jmx.enabled=true -Dspring.liveBeansView.mbeanDomain -Dspring.application.admin.enabled=true -javaagent:/Applications/IntelliJ IDEA.app/Contents/lib/idea_rt.jar=57585:/Applications/IntelliJ IDEA.app/Contents/bin -Dfile.encoding=UTF-8"

  jvmFlags = N/A

  javaArguments = "org.springframework.samples.petclinic.PetClinicApplication"

  jvmStartTime = 10:51:03.951

  pid = 97704
}
```

**Comment by jasonjkeller** [comment]
Also see conversation [here](https://github.com/newrelic/newrelic-jfr-core/pull/126#discussion_r546916614)

**Comment by XiXiaPdx** [comment]
The maximum length of an attribute value is 4096 characters. 
https://docs.newrelic.com/docs/telemetry-data-platform/ingest-manage-data/ingest-apis/introduction-event-api/#limits

**Comment by XiXiaPdx** [comment]
proposed solution - https://newrelic.slack.com/archives/CV2EXQQA2/p1619028903005500
